# Generated by Django 4.1.5 on 2023-01-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active_user',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='admin_user',
            new_name='is_staff',
        ),
    ]
