# Generated by Django 4.1.5 on 2023-01-18 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0002_book_description_book_image_book_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_days', models.SmallIntegerField(default=7, verbose_name='Number of days to reserve')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Reservation expiration date')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
